### ISSUE TITLE
UCK Gen-1 partially update/auto-reboot

### ISSUE THREAD

**Issue by MarkRoks** [agreenbhm/Unifi-CloudKey#1]
Hello,

I managed to update my UCK Gen-1 to firmware 8.6.9 using the manual. At least that's what I see when I enter the IP address in the URL. 

But when I then log in to the Unifi Controller software (with port 8443), it shows firmware 7.2.97. I can't get it updated from the Unifi Controller.

Do I need to do anything else somewhere so that the Unifi Controller also goes to firmware 8.6.9?

In addition, the Unifi Controller Software does not start automatically after a restart. This must be forced using "service unifi start". It would be nice if an auto-reboot function could be created.

I'd like to hear it.

Greetings, Mark

**Comment by agreenbhm** [comment]
Hi Mark, let me take a look at my system here when I get a chance and see if I can replicate this.

**Comment by MarkRoks** [comment]
Hello Green,

I have gone through the workaround a number of times, but ultimately cannot get it to firmware 8.6.9. After which I reset it to factory settings and try again.

I see it's running on Debian Buster. I managed to upgrade it to Bullsey once. Possibly this is why it doesn't release on 8.6.9?

If you have a different or addition to the existing workaround, please let me know.

Greetings,

Mark

**Comment by MarkRoks** [comment]
Hello Green,

I have already discovered something. Under "Upgrading" it says: ./upgrade_cloudkey.sh. But this doesn't work. I replaced this with:

- cd Unifi-CloudKey-main
- chmod +x ./upgrade_cloudkey.sh
- sudo ./upgrade_cloudkey.sh. 

And something is being done here. I see "Bullseye" passing by a number of times. I suspect that this debian should be used for firmware 8.6.9.

In addition, I suspect that the Unifi Controller must first be stopped before performing the above. I use "service unifi stop" for this. However, it takes about 30 minutes with various updates. 

However, the result is that it (again) boots on firmware 7.2.97. 

Perhaps you can do something with this?

Greetings, Mark

**Comment by MarkRoks** [comment]
Hello Green,

I was able to trace something back. Installing Docker, including Unifi 8.6.9 firmware, is possible on the UCK. After logging in to the UCK, this is also indicated in the installed version of the Unifi Controller on the UCK.

However, the Unifi Controller does not start automatically, which it did in the older versions (until 7.2.97). This may be because it runs in Docker. This also explains why it cannot be started from the UCK web browser (using the "Start Unifi" button).

When I start it from SSH (using: "service unifi start"), it starts the Unifi Controller, but falls back to the older firmware 7.2.97. And in the UCK web browser it indicates "not installed" under Unifi. So it seems to fall back on this firmware in Docker.

This may help find the cause. 

I'd like to hear it.

Greetings,

Mark

**Comment by MarkRoks** [comment]
Hello Green,

I've been testing everything over the past few weeks. 

What I see is that the Unifi in the container is restarted approximately every 30 seconds and therefore never comes online.

When I search the internet, I mainly find that the Unifi Controller software (firmware 8.6.9) does not work under Java-8. I have not yet been able to update/adjust this.

In the UCK-web-page he indicates that he is "stopped". And starting it manually does not offer a solution.

I suspect that something goes wrong in the startup script, causing it to keep restarting. It is possible that the Java version also has an influence, but of course I don't know for sure.

Perhaps you can do something with the above information?

I'd like to hear it.

Greetings,

Mark

**Comment by FHannes** [comment]
I am seeing the same issue. The container keeps failing to start with the following exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/beans/factory/InitializingBean
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.InitializingBean
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 10 more
Starting UniFi Network Application: unifi failed!
```

**Comment by MarkRoks** [comment]
> Ik zie hetzelfde probleem. De container start steeds niet met de volgende uitzondering:
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/beans/factory/InitializingBean
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> 	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.InitializingBean
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> 	... 10 more
> Starting UniFi Network Application: unifi failed!
> ```

I haven't tried that for a while, but in the meantime there has been a Unifi update from 8 to 9.

I hope that there will be a solution (still) to be able to use the UCK Gen-1, using the latest Unifi software.

**Comment by isaiapasca** [comment]
Has anyone managed to get this going?

I encounter similar problems with the above posts, after install , or update the web interface of the network server doe snot come online, and if the "service unifi start" it starts the Original  version 7.x

i can see downloading version 9.x but i think there might be a command to run that, the owner of the project might be able to help with corect commands?

any help would be appreciated so people can actually use this piece of software :)

**Comment by isaiapasca** [comment]
after resetting key and installing everything fresh using tutorial provided, after restart if i login to the key via ssh and run:

root@UniFi-CloudKey:~ docker-compose up -d
no configuration file provided: not found
root@UniFi-CloudKey:~

soo docker does not start

**Comment by ipp0** [comment]
> I am seeing the same issue. The container keeps failing to start with the following exception:
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/beans/factory/InitializingBean
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> 	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.InitializingBean
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> 	... 10 more
> Starting UniFi Network Application: unifi failed!
> ```

I get this same issue. Is some library missing from Debian?

**Comment by isaiapasca** [comment]
I did gave up on this as it did not seem to work for me.

From what i can see this project is not looked after anymore, it is a shame as the idea was good.

**Comment by agreenbhm** [comment]
Unfortunately my time these days to troubleshoot this are limited so I haven't been able to look at updating the project. That said, I can guess as to what might be happening:

This was originally released for Unifi 8.x, but it seems like 9.x has since been released by Ubiquiti. The reason I was able to get 8.x working on the UCK1 is that a native JNI library needed for ARMv7 support was able to be taken from the UCK1 install and put into the unsupported version package of the Unifi server. As Java is platform independent (with the exception of native libraries), so long as that required native library is available, with my hack, the code will run. This setup relies on the native library not changing. If the 9.x series (or previous versions, past what I originally tested with) changed that library at all then the old ARMv7 one won't work with the newer server. 

I recommend someone use this as a jumping off point and at a minimum check the MD5 of the native libraries in the new server against those of the latest supported UCK1 server. Compare the ones that are present in both (ie ARMv8); if that matches then hopefully the ARMv7 library is still compatible. Also, the file "ace.jar" was edited to allow running on ARMv7 (as IIRC the original prevented running there just by a simple boolean check). It's possible the old ace.jar file is incompatible with current versions and needs to be patched to allow ARMv7. However, that part is not relevant if the native library is incompatible, so start with that before looking at ace.jar.

**Comment by ipp0** [comment]
The project seems to work fine if I change provision_cloudkey.sh and docker-compose.yml to refer to agreenbhm/unifi-cloudkey:8.4.59-26648-1 instead of latest. I don’t think any other files are needed to install. Maybe these files should be changed so that the installation works even if it’s not the latest version. The installation instructions could also be updated to only download these two files.

**Comment by agreenbhm** [comment]
> The project seems to work fine if I change provision_cloudkey.sh and docker-compose.yml to refer to agreenbhm/unifi-cloudkey:8.4.59-26648-1 instead of latest. I don’t think any other files are needed to install. Maybe these files should be changed so that the installation works even if it’s not the latest version. The installation instructions could also be updated to only download these two files.

Please make a PR with your suggested changes.

**Comment by isaiapasca** [comment]
Please let us know when the project is fixed and works as i would be interested to try this again.

**Comment by isaiapasca** [comment]
For others who want to use this software! you only need 2 files, no need to download the tar.gz file. 
whole setup process below:

I have reset to default the key, then i logged via SSH, user/pass  ubnt/ubnt

Stop the service then continue with setup.

`service unifi stop`


```
mkdir /root/unifi-fix
cd /root/unifi-fix

wget https://raw.githubusercontent.com/agreenbhm/Unifi-CloudKey/main/docker-compose.yml
wget https://raw.githubusercontent.com/agreenbhm/Unifi-CloudKey/main/provision_cloudkey.sh
```

then edit:

`vi docker-compose.yml`

```
version: '3.8'

services:
  mongodb:
    image: agreenbhm/unifi-cloudkey:8.4.59-26648-1
    container_name: mongodb
    hostname: mongodb
    network_mode: host
    restart: unless-stopped
    volumes:
      - /srv/unifi/var/lib/mongodb:/var/lib/mongodb
    command: /etc/init.d/mongodb start
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "27117"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  unifi:
    image: agreenbhm/unifi-cloudkey:8.4.59-26648-1
    container_name: unifi
    hostname: unifi
    network_mode: host
    restart: unless-stopped
    volumes:
      - /srv/unifi/var/lib/unifi:/var/lib/unifi
    command: /etc/init.d/unifi start
    depends_on:
      mongodb:
        condition: service_healthy


```

`vi provision_cloudkey.sh`

```
#!/bin/bash

if [ "$EUID" -ne 0 ]
then
        echo "Please re-run with root privileges."
        exit
fi

mode="$1"

# Info messages in yellow
info() {
    command echo -e "\e[1;33m$@\e[0m"
}

# Success messages in green
success() {
    command echo -e "\e[1;32m$@\e[0m\n\n"
}

# Error messages in red
error() {
    echo -e "\e[1;31m$@\e[0m" >&2
}
exec 2> >(while read -r line; do error "$line"; done)

# Shutting off pre-installed Unifi and MongoDB
info "Disabling stock Unifi and database..."
systemctl disable unifi && systemctl stop unifi
systemctl disable mongodb && systemctl stop mongodb
success "Done"

# Skip setting repos if provisioning in VM mode
if [ "$mode" != "vm" ]
then
        # Existing Debian repo lists are outdated and don't work; replacing with working ones and adding additional ones
        info "Backing up repo lists and installing new ones..."
        mv /etc/apt/sources.list /etc/apt/sources.list.old
        mv /etc/apt/sources.list.d /etc/apt/sources.list.d.old
        echo 'deb https://download.docker.com/linux/debian jessie stable' > /etc/apt/sources.list
        #echo 'deb [ arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti' >> /etc/apt/sources.list
        echo 'deb http://archive.debian.org/debian-security jessie/updates main contrib non-free' >> /etc/apt/sources.list
        echo 'deb http://archive.debian.org/debian/ jessie main contrib non-free' >> /etc/apt/sources.list
        success "Done"
fi

info "Updating apt and installing Docker and dependencies..."
# Fixing missing /dev/tty[0-9] requirement of some dependency.
# This doesn't do anything, but fixes install/config errors.
touch /dev/tty0
# Moving Docker dir to /srv/ partition to account for limited userdata space
systemctl stop docker
mkdir -p /srv/var/lib/docker
if [ -d "/var/lib/docker" ]
then
        mv /var/lib/docker /srv/var/lib/
fi
ln -sf /srv/var/lib/docker /var/lib/docker
apt update
if [ "$mode" != "vm" ]
then
        apt -yf install docker-ce
        success "Done"
        # There's some weird issue introduced with Docker 18.06.2 to address a CVE which
        # breaks Docker on this device.  18.06.1 works though.  Installing latest from repo and then
        # downgrading from .deb allows installation of dependencies.
        info "Downgrading Docker to working version and installing docker-compose..."
        wget https://download.docker.com/linux/debian/dists/jessie/pool/stable/armhf/docker-ce_18.06.1~ce~3-0~debian_armhf.deb
        dpkg -i docker-ce_18.06.1~ce~3-0~debian_armhf.deb
        wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-compose-plugin_2.6.0~debian-buster_armhf.deb
        dpkg -i docker-compose-plugin_2.6.0~debian-buster_armhf.deb
        ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/
else
        apt -yf install docker.io docker-compose
fi
success "Done"

# There's some weird issue introduced with Docker 18.06.2 to address a CVE which
# breaks Docker on this device.  18.06.1 works though.  Installing latest from repo and then
# downgrading from .deb allows installation of dependencies.
#info "Downgrading Docker to working version and installing docker-compose..."
#wget https://download.docker.com/linux/debian/dists/jessie/pool/stable/armhf/docker-ce_18.06.1~ce~3-0~debian_armhf.deb
#dpkg -i docker-ce_18.06.1~ce~3-0~debian_armhf.deb
#wget https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/docker-compose-plugin_2.6.0~debian-buster_armhf.deb
#dpkg -i docker-compose-plugin_2.6.0~debian-buster_armhf.deb
#ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/
#success "Done"


# Checking Unifi version via the MongoDB container so version is still available if the Unifi
# container is stopped, which is necessary for the webui.
# Changing service start/stop functions to call Docker instead of the host's service.
# Known Issue - the Maintenance page might show the service as stopped for an extended length
# of time after clicking 'Start' as it takes a while for the container to start.
info "Making changes to host system webui to support new Unifi version in Docker..."
usermod -a -G docker www-data
cp /usr/share/cloudkey-webui/www/common.inc /usr/share/cloudkey-webui/www/common.inc.bak
cp /usr/share/cloudkey-webui/www/settings.inc /usr/share/cloudkey-webui/www/settings.inc.bak
cp /usr/share/cloudkey-webui/www/api.inc /usr/share/cloudkey-webui/www/api.inc.bak
#sed -i "s/\$cmd = 'dpkg-query/\$cmd = 'docker exec -t unifi dpkg-query/g" /usr/share/cloudkey-webui/www/common.inc
sed -i "s/\$cmd = 'dpkg-query/\$cmd = 'docker exec -t mongodb dpkg-query/g" /usr/share/cloudkey-webui/www/common.inc
echo '* * * * * /usr/bin/touch /var/run/unifi_runtime.cfg' >> /var/spool/cron/crontabs/root
# if [ ! -f "/etc/rc.local" ]
# then
#       echo -e '#!/bin/sh\n\nexit 0' > /etc/rc.local
#       chmod +x /etc/rc.local
# fi
#sed -i 's/^exit 0$/touch \/var\/run\/unifi_runtime.cfg\nexit 0/g' /etc/rc.local
sed -i "s/.*CMD_SERVICE_UNIFI.*/define('CMD_SERVICE_UNIFI', '\/usr\/bin\/docker ');/g" /usr/share/cloudkey-webui/www/settings.inc
sed -i "s/exec(CMD_SERVICE_UNIFI . ' start', \$out, \$rc);/exec(CMD_SERVICE_UNIFI . ' start unifi', \$out, \$rc);/g" /usr/share/cloudkey-webui/www/api.inc
sed -i "s/exec(CMD_SERVICE_UNIFI . ' stop', \$out, \$rc);/exec(CMD_SERVICE_UNIFI . ' stop unifi', \$out, \$rc);/g" /usr/share/cloudkey-webui/www/api.inc
success "Done"

# info "Building Docker image - this will probably take a while..."
# docker build -t agreenbhm/unifi-cloudkey:latest --network host .
# success "Done"

info "Pulling Docker image..."
docker pull agreenbhm/unifi-cloudkey:8.4.59-26648-1
success "Done"

info "Starting containers..."
docker-compose up -d
success "Finished!"

error "Need to reboot. Please do so manually."

```

```
chmod +x provision_cloudkey.sh
./provision_cloudkey.sh
```

reboot, and you are good to go: 
`reboot`
wait a while (5 minutes)


to login go to https://Key-Local-IP/8443
Enjoy!

**Comment by spam1998** [comment]
Hi looks like the version 8.4.59 is last witch can run on UCK1 with  use  docker
